baseurl = "/"
languageCode = "en-us"
languageLang = "en"
title = "Amy Lynn Green"

[params]
  author = "Amy Lynn Green"
  description = "Amy Lynn Green is a lifelong lover of books, history, and library cards. She worked in publishing for six years before writing her first historical fiction novel, based on the WWII home-front of Minnesota, the state where she lives, works, and survives long winters."
  ogimage = "/img/og-image.jpg"
  facebook = "https://www.facebook.com/amygreenbooks/"
  instagram = "https://www.instagram.com/amygreenbooks/"

# RSS, categories and tags disabled for an easy start
# See configuration options for more details:
# https://gohugo.io/getting-started/configuration/#toml-configuration
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]
