backend:
  name: git-gateway

media_folder: "site/static/img" # Folder where user uploaded files should go
public_folder: "/img"

collections: # A list of collections the CMS should be able to edit
  - name: "news" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "News" # Used in the UI, ie.: "New Post"
    folder: "site/content/news" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Intro Blurb", name: "description", widget: "text"}
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "books"
    label: "Books"
    label_singular: "Book"
    folder: "site/content/books"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Create Date", name: "date", widget: "datetime"}
      - {label: "Release Date", name: "releaseDate", widget: "datetime"}
      - {label: "Summary", name: "description", widget: "text"}
      - {label: "Cover Image", name: "image", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
      - label: Retailers
        name: retailers
        label_singular: Retailer
        widget: list
        fields:
          - {label: Name, name: name, widget: string}
          - {label: Link, name: link, widget: string}
          - {label: Image, name: imageUrl, widget: image}
      - label: Endorsements
        name: endorsements
        label_singular: endorsement
        widget: list
        fields:
          - {label: Author, name: author, widget: string}
          - {label: Quote, name: quote, widget: text}
  - name: "pages"
    label: "Pages"
    files:
      - file: "site/content/_index.md"
        label: "Home Page"
        name: "home"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Subtitle, name: subtitle, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: "Welcome", name: welcome, widget: object, fields: [
              {label: "Heading", name: "heading", widget: string},
              {label: "Text", name: "text", widget: "markdown"},
              {label: "Image", name: "imageUrl", widget: "image"}]}
      - file: "site/content/contact/_index.md"
        label: "Contact Page"
        name: "contact"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Body, name: body, widget: markdown}
          - label: Contact Entries
            name: contact_entries
            widget: list
            fields:
              - label: Heading
                name: heading
                widget: string
              - label: Text
                name: text
                widget: text
