backend:
  name: git-gateway

media_folder: "public/media" # Folder where user uploaded files should go
public_folder: "/media"

collections: # A list of collections the CMS should be able to edit
  - name: "books"
    label: "Books"
    label_singular: "Book"
    folder: "content/books"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "ISBN", name: "isbn", widget: "string" }
      - {
          label: "Create Date",
          name: "date",
          widget: "datetime",
          format: "YYYY-MM-DDTHH:mm:ss",
        }
      - {
          label: "Release Date",
          name: "releaseDate",
          widget: "datetime",
          format: "YYYY-MM-DD",
          time_format: false,
        }
      - { label: "Summary", name: "description", widget: "text" }
      - {
          label: "Cover Image",
          name: "image",
          widget: "image",
          required: false,
        }
      - { label: "Body", name: "body", widget: "markdown" }
      - label: Retailers
        name: retailers
        label_singular: Retailer
        widget: list
        fields:
          - { label: Name, name: name, widget: string }
          - { label: Link, name: link, widget: string }
          - { label: Image, name: image, widget: image }
      - label: Endorsements
        name: endorsements
        label_singular: endorsement
        widget: list
        fields:
          - { label: Author, name: author, widget: "markdown" }
          - { label: Quote, name: quote, widget: "markdown" }
  - name: "landingPages"
    label: "Landing Pages"
    label_singular: "Landing Page"
    folder: "content/pages"
    create: true
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Subtitle, name: description, widget: string }
      - { label: "Banner Image", name: bannerImage, widget: image }
      - { label: Body, name: body, widget: markdown }
  - name: "pages"
    label: "Default Pages"
    files:
      - file: "content/index.md"
        label: "Home Page"
        name: "home"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Subtitle, name: subtitle, widget: string }
          - { label: "Banner Image", name: bannerImage, widget: image }
          - {
              label: "Welcome",
              name: welcome,
              widget: object,
              fields:
                [
                  { label: "Heading", name: "heading", widget: string },
                  { label: "Text", name: "text", widget: "markdown" },
                  { label: "Image", name: "image", widget: "image" },
                ],
            }
      - file: "content/contact.md"
        label: "Contact Page"
        name: "contact"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Subtitle, name: description, widget: string }
          - { label: "Banner Image", name: bannerImage, widget: "image" }
          - {
              label: "Success Message",
              name: successMessage,
              widget: "markdown",
            }
          - { label: Body, name: body, widget: markdown }
      - file: "content/about.md"
        label: "About Page"
        name: "about"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Image, name: aboutImage, widget: "image" }
          - { label: Body, name: body, widget: markdown }
